<h1 style="text-align: center;">Simulación y aplicaciones en ciencias sociales y experimentales
</h3>
<h3 style="text-align: center;"> Tema 3. Modelos aleatorios </h3>
<h3 style="text-align: center;"> Cadenas de Markov</h3>

Una cadena de Markov es un tipo de proceso estocástico. Así, antes de comenzar con la modelización, introduzcamos estos conceptos generales previos:

Un **proceso estocástico** es un conjunto de variables aleatorias $\{X_t\}_{t \in T}$, donde $T$ suele representar el tiempo. En su versión discreta $T$ es un subconjunto de los números naturales. La version aleatoria de los modelos SIR de difusión de una enfermedad son ejemplos de procesos estocásticos donde $X_t$ puede ser el número de infectados en cada instante del tiempo. 

Los posibles valores $x_t$ de un proceso estocástico $X_t$ se les llama **estados**, y cuando los estados se encuentran en un espacio discreto al proceso estocástico se le denomina **cadena**. Generalmente, los estados $x_t$ de un proceso estocástico dependen de los estados en fases anteriores del tiempo. Cuando ese estado depende exclusivamente del estado en el instante anterior se dice que estamos ante una **cadena de Markov**. Escrito en tiempo discreto una cadena de Markov satisface la siguiente propiedad: 

 $$P[X_{t+1}=x_{t+1}/X_{t}=x_{t},X_{t-1}=x_{t-1},...,X_0=x_0] = P[X_{t+1}=x_{t+1}/X_{t}=x_{t}].$$

Escrito en tiempo continuo, la propiedad sería que dados los instantes $t_1<t_2<...<t_{k}$ pertenecientes a $T$, se verifica: 

$$P[X(t_k)=i_k/X(t_{k-1})=i_{k-1},..., X(t_1)=i_1] = P[X(t_k)=i_k/X(t_{k-1})=i_{k-1}],$$

para todo $i_1$, $i_2$,..., $i_k$ estados. 
 
A modo de ejemplo, ¿es el modelo SIR estocástico una cadena de Markov?

### Cadenas de Markov discretas

En una cadena de Markov discretas, se define la **probabilidad conditional $p_{ij}(n)$** a la probabilidad de que el proceso esté en el estado $i$ en el instante $n$ y en el estado $j$ en el instante $n+1$. Esto es: 
$$p_{ij}(n) = P[X_{n+1}=j/X_{n}=i].$$
Se dice que una cadena de Markov es **homogénea** cuando las probabilidades de pasar de un estado a otro son independientes del tiempo, esto es $p_{ij}(n) = p_{ij}$, $\forall i,j$ estados cualesquiera. 

### Ejercicio 1

La predicción del tiempo pudiera modelarse a través de una cadena de Markov. Supóngase que hay tres tipos de estados: soleado (S), nublado (C) y lluvioso (R). El tiempo se observa cada día. La probabilidad de que haya un día soleado despues de otro día soleado es 0.8 y de que sea nublado 0.15. La probabilidad de que haya un día nublado después de otro nublado es 0.2 y soleado 0.7. La probabilidad de que haya un día lluvioso después de otro lluvioso es 0.2, y que sea soleado 0.5.  

**a)** Supóngase que hoy es un día nublado. Indicar la probabilidad a largo plazo de que el día sea soleado, nublado o lluvioso; **b)** Asumir una predicción cualquiera para el día de hoy y calcular de nuevo la probabilidad a largo plazo de que el día sea soleado, nublado o lluvioso. Indicar si esta probabilidad depende del pronóstico actual. **c)** Si el pronóstico del tiempo indica que hoy hay $\alpha_1$% de posibilidades de que sea soleado, $\alpha_2$% de posibilidades de que sea nublado y $\alpha_3$% de posibilidades de que sea lluvioso, indicar la expresión que determina el pronóstico del tiempo al día siguiente.

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
P = np.array([
    [0.8, 0.15, 0.05],
    [0.7, 0.2, 0.1],
    [0.5, 0.3, 0.2]
])

# Paso 1: Calcular la probabilidad a largo plazo (Ejercicio a y b)

# Definimos una función para calcular la distribución estacionaria o límite
def stationary_distribution(P, pi_0, tolerance=1e-8, max_iterations=1000):
    pi = pi_0.copy()
    for _ in range(max_iterations):
        pi_next = pi @ P
        if np.allclose(pi_next, pi, atol=tolerance):
            break
        pi = pi_next
    return pi

# Distribución inicial para "día nublado" (Ejercicio a)
pi_0_nublado = np.array([0, 1, 0])
stationary_nublado = stationary_distribution(P, pi_0_nublado)

# Distribución inicial general uniforme (Ejercicio b)
pi_0_general = np.array([1/3, 1/3, 1/3])
stationary_general = stationary_distribution(P, pi_0_general)

# Imprimir los resultados de las probabilidades a largo plazo
print("Probabilidad a largo plazo con día inicial nublado:")
print(f"Soleado: {stationary_nublado[0]:.4f}, Nublado: {stationary_nublado[1]:.4f}, Lluvioso: {stationary_nublado[2]:.4f}\n")

print("Probabilidad a largo plazo con distribución inicial general:")
print(f"Soleado: {stationary_general[0]:.4f}, Nublado: {stationary_general[1]:.4f}, Lluvioso: {stationary_general[2]:.4f}\n")

# Paso 2: Calcular el pronóstico del tiempo al día siguiente (Ejercicio c)

# Definir una función para calcular el pronóstico
def next_day_forecast(alpha, P):
    return np.array(alpha) @ P

# Pronóstico del tiempo hoy (distribución inicial)
alpha_today = [0.5, 0.3, 0.2]  # 50% soleado, 30% nublado, 20% lluvioso
forecast_tomorrow = next_day_forecast(alpha_today, P)

# Imprimir el pronóstico para mañana
print("Pronóstico para mañana dado el pronóstico de hoy (50% Soleado, 30% Nublado, 20% Lluvioso):")
print(f"Soleado: {forecast_tomorrow[0]:.4f}, Nublado: {forecast_tomorrow[1]:.4f}, Lluvioso: {forecast_tomorrow[2]:.4f}")


Probabilidad a largo plazo con día inicial nublado:
Soleado: 0.7625, Nublado: 0.1688, Lluvioso: 0.0688

Probabilidad a largo plazo con distribución inicial general:
Soleado: 0.7625, Nublado: 0.1688, Lluvioso: 0.0688

Pronóstico para mañana dado el pronóstico de hoy (50% Soleado, 30% Nublado, 20% Lluvioso):
Soleado: 0.7100, Nublado: 0.1950, Lluvioso: 0.0950


#### Matriz de transición

Una cadena de Markov homogénea puede representarse a través de la llamada **matriz de transición**, que incluye sus probabilidades estacionarias de la forma: 

$$ P = \left[ \begin{array}{cccc} p_{11} & p_{12} & \cdots & p_{1k}\\ p_{21} & p_{22} & \cdots & p_{2k} \\ \cdots & \cdots & \cdots & \cdots \\ p_{k1} & p_{k2} & \cdots & p_{kk}\end{array} \right],$$

donde se ha asumido un número $k$ finitos de estados. La matriz de transición verifica dos propiedades: 
- Todos los términos $p_{ij} \geq 0$.
- La suma de los valores de las filas es 1, esto es, $\sum_{j=1}^k p_{ij} =1$.

Una matriz que verifica estas propiedades se le denomina **matriz estocástica**. Es fácil demostrar que $\lambda=1$ es un valor propio de una matriz estocástica y que todos los demás valores propios son menores que 1 en valor absoluto. 

#### Estados transitorios de una cadena de Markov

Asúmase una distribución inicial de estados $\pi_0 = [\pi_0^1,\pi_0^2,...,\pi_0^k]$, con $\pi_0^i$ la probabilidad de que la cadena de Markov esté en el estado $i$ en $t=0$. Es sencillo demostar que la distribución de los estados en $t=1$, $\pi_1$, es igual a: 
$$\pi_1 = \pi_0 P.$$
Siguiendo el mismo procedimiento por recurrencia, tenemos que la distribución de los estados en el tiempo $n$, $\pi_n$, es igual a:
$$\pi_n = \pi_0 P^n.$$

#### Distribución estacionaria y distribución límite 

A partir de la fomra de hallar la distribución sucesiva de estados, se plantean dos maneras de encontrar una distribución de estados que no evoluciona en el tiempo. 

1) Una **distribución estacionaria $z$** es aquella cumple:
   $$zP=z.$$

O sea, una distribución estacionaria es un vector propio a la izquierda con valor propio 1. 

2) Una **distribución límite $\pi^*$** es la obtenida cuando $n\rightarrow \infty$. Esto es,
   $$\pi^*= \lim_{n\rightarrow \infty} \pi_n = \pi_0 \lim_{n\rightarrow \infty} P^n.$$

Por tanto, para que existe la distribución límite de una cadena de Markov finita es necesario que exista $\lim_{n\rightarrow \infty} P^n.$

Es deseable que tanto la distribución estacionaria como la distribución límite existan y coincidan. Sin embargo, esto no es así en general. Definamos un tipo de cadena de Markov que sí lo cumple. 

**Definición:** Una cadena de Markov se dice **regular** si existe un $m>0$ tal que todos los componentes de $P^m$ son positivos. Dicho de otra manera, es una matriz en la que existe un momento donde es posible la transición en un solo paso a todos los estados del sistema.

Ya estamos en disposición de presentar el siguiente teorema que asegura la igualdad entre la distribución estacionaria y la límite. 

**Teorema:** Si una cadena de Markov es regular, entonces se verifica que las distribuciones estacionarias $z$ y límite $\pi^*$ coinciden y son únicas. Además $\lim_{n\rightarrow \infty} P^n= P^*$ es una matriz con todas las filas iguales a $z$, y cada elemento $j$ de $z$ indica la probabilidad a largo plazo de que el sistema se encuentre en el estado $j$. 

### Ejercicio 1 (continuación)

Verificar que la matriz de transición es regular. Comprobar que la distribución estacionaria $z$ coincide con la distribución límite $\pi^*$ y verificar que $P^*$ es una matriz con todas las filas iguales a $z$. 

In [15]:
import numpy as np

# Definir la matriz de transición
P = np.array([
    [0.8, 0.15, 0.05],
    [0.7, 0.2, 0.1],
    [0.5, 0.3, 0.2]
])

# Verificar si la matriz de transición es regular
def is_regular(P, max_power=100):
    for m in range(1, max_power + 1):
        P_m = np.linalg.matrix_power(P, m)
        if np.all(P_m > 0):  # Si todos los elementos de P^m son positivos
            return True, m
    return False, None

# Calcular la matriz P^* (límite de P^n)
def limit_matrix(P, tolerance=1e-8, max_iterations=1000):
    P_n = P.copy()
    for _ in range(max_iterations):
        P_next = P_n @ P
        if np.allclose(P_next, P_n, atol=tolerance):
            break
        P_n = P_next
    return P_n

# Verificar si la matriz es regular
is_regular_result, power = is_regular(P)

# Calcular la matriz límite P^*
P_star = limit_matrix(P)

# Extraer la distribución estacionaria z
z = P_star[0]  # Todas las filas de P^* deben ser iguales, así que tomamos la primera

# Comprobar que z es un vector propio a la izquierda con valor propio 1
is_stationary = np.allclose(z @ P, z)

# Resultados
print(f"La matriz de transición es regular: {is_regular_result} (m={power})")
print("\nMatriz límite P^*:") 
print(P_star.round(4))
print("\nDistribución estacionaria z:")
print(z.round(4))
print(f"\n¿La distribución estacionaria z coincide con la propiedad zP=z?: {is_stationary}")


La matriz de transición es regular: True (m=1)

Matriz límite P^*:
[[0.7625 0.1687 0.0687]
 [0.7625 0.1688 0.0688]
 [0.7625 0.1688 0.0688]]

Distribución estacionaria z:
[0.7625 0.1687 0.0687]

¿La distribución estacionaria z coincide con la propiedad zP=z?: True


## Referencias

- Spong, M.W. (2023). Introduction to Modeling and Simulation. A Systems Approach. Wiley.
- Stewart, W. J. (2009). Probability, Markov Chains, Queues, and Simulation. Princenton University Press. 

